# Generated by Django 3.1.4 on 2020-12-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=50)),
                ('content1', models.CharField(max_length=200)),
                ('date1', models.DateField(blank=True)),
                ('time1', models.TimeField(blank=True)),
            ],
        ),
    ]
