# Generated by Django 3.1.2 on 2020-12-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary_app', '0002_monthly_yearly'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthly',
            name='box3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='yearly',
            name='box2',
            field=models.IntegerField(default=0),
        ),
    ]
