# Generated by Django 3.1.2 on 2020-12-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary_app', '0003_auto_20201213_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthly',
            name='box3',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='yearly',
            name='box2',
            field=models.IntegerField(default=1),
        ),
    ]
