# Generated by Django 3.1.2 on 2020-12-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary_app', '0004_auto_20201213_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='year1',
            field=models.IntegerField(default=2021),
        ),
        migrations.AlterField(
            model_name='monthly',
            name='box3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='yearly',
            name='box2',
            field=models.IntegerField(default=0),
        ),
    ]
